### ISSUE TITLE
http.nonProxyHosts support

### ISSUE THREAD

**Issue by NicholasScott** [googleapis/java-pubsub-group-kafka-connector#265]
Hi,

Does this connector support the -Dhttp.nonProxyHosts option, I can see there are instructions for using a proxy by specifying the JVM options for host and port, however we also need to be able to specify a list of nonProxyHosts as we are working with an OnPremise kafka cluster which is talking to GCP via a proxy, however the licensing servers for the kafka cluster are based OnPremise and shouldn't go through that proxy. We have had problems with the confluent provided pubsub kafka connector as it ignores the nonProxyHosts jvm parameter so we were interested in trying out this one to see if it correctly handles it.

**Comment by samarthsingal** [comment]
Hi Nicholas - 

The connector will ultimately run packaged with the Kafka Connect binary and relies on the network client/server provided. Please note that Kafka traffic is non-HTTP and uses a custom TCP-based binary protocol - https://kafka.apache.org/0100/protocol.html#protocol_network. This should not be affected by the HTTP proxy setting (if it is restricted correctly to HTTP-only traffic). Please note that it is likely that you have configured [authentication with SASL/SSL](https://kafka.apache.org/documentation/#security) and so might need to allow inbound/outbound traffic of that type to the broker addresses.
