### ISSUE TITLE
Configuring Multiple Kafka Topics

### ISSUE THREAD

**Issue by chadleeshaw** [googleapis/java-pubsub-group-kafka-connector#282]
In most of the examples there is a direct topic to topic configuration.  I am struggling to understand how I can configure a list of multiple topics to sink from Kafka and publish to pub/sub with the same topic name IE:

```
{
  "name": "kafka-pubsub",
  "config": {
    "connector.class": "com.google.pubsub.kafka.sink.CloudPubSubSinkConnector",
    "consumer.auto.offset.reset": "latest",
    "topics":  "topic1, topic2, topic3"
    "tasks.max": 1,
    "cps.project": "project1",
    "cps.topic": "topic1, topic2, topic3"
  }
}
```
Is it possible to configure `cps.topic` with a variable that represents the original topic from Kafka?
The obvious solution is to break these up and use separate configs, however because you use the name field as the consumer group I can't as it doesn't allow duplicate names... Unless I want a bunch of consumer groups.

**Comment by samarthsingal** [comment]
It is only possible to configure one `cps.topic` per sink configuration.

> however because you use the name field as the consumer group I can't as it doesn't allow duplicate names... Unless I want a bunch of consumer groups.
Is there a use-case you have for using the same consumer-group across different topics? Please note that each connector gets independent tasks without any coordination so having the same consumer group does not yield any benefit.

**Comment by chadleeshaw** [comment]
Thanks for a response, the main purpose if for simplicity when there is a large number of topics and also monitoring consumer lag.

**Comment by samarthsingal** [comment]
Unfortunately, I dont think there's a general way for CPS to interprety multiple destination topics. In your example, you use the same topic names:
```
"topics":  "topic1, topic2, topic3"
"cps.topic": "topic1, topic2, topic3"
```
But there is no requirement for users to have the same topic names in CPS and Kafka. Furthermore, consider a 1-to-many mapping or a an unequal number - how would CPS know what subset of messages to send where. 

If you have examples of other connectors that have done this, we can explore but as it stands I dont think this is a feasible feature request so I will close it.
