### ISSUE TITLE
Kafka connector has dependency issues

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/java-pubsub-group-kafka-connector#30]
To repro the dependency issues reported by GitHub Actions, please refer to https://github.com/googleapis/java-pubsub-group-kafka-connector/blob/main/.kokoro/dependencies.sh as configured below (L63).

https://github.com/googleapis/java-pubsub-group-kafka-connector/blob/df9fffea3952dedd354d25cc339945a03b8523a9/.github/workflows/ci.yaml#L51-L63

**Comment by samarthsingal** [comment]
Where are the dependency issues reported? Does it specify which version of Kafka is not compatible?

**Comment by anguillanneuf** [comment]
@samarthsingal Test run details can be viewed in any outstanding PRs. Or even on the main branch, check out any commit's test statuses. 

![Screen Shot 2022-07-13 at 2 30 09 PM](https://user-images.githubusercontent.com/9518298/178839896-aaea8e65-5cc8-4da8-8dde-ff5fff1bb53c.png)
